# Generated by Django 4.1.6 on 2023-03-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0002_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
