# Generated by Django 4.1.6 on 2023-03-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0003_news_date_news_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='empty', upload_to='news'),
            preserve_default=False,
        ),
    ]
