# Generated by Django 4.1.6 on 2023-03-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0004_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(max_length=100000),
        ),
    ]
