# Generated by Django 4.1.6 on 2023-03-21 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=None)),
                ('link', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('months', models.IntegerField()),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser.adstype')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser.advertiser')),
            ],
        ),
    ]
