# Generated by Django 4.1.6 on 2023-03-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0002_adstype_ads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='user',
        ),
    ]
