# Generated by Django 4.1.6 on 2023-03-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0004_alter_ads_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
